language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
  - '6'
before_script:
  - npm i nyc -g
  - npm i coveralls -g
script:
  - npm run coverage
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
